const mix = require("laravel-mix");

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel applications. By default, we are compiling the CSS
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.styles(
    [
        "resources/assets/css/all.min.css",
        "resources/assets/css/bootstrap.min.css",
        "resources/assets/css/admin-style.css",
    ],
    "public/assets/css/admin/admin_style.min.css"
)
    .styles(
        [
            "resources/assets/css/all.min.css",
            "resources/assets/css/bootstrap.min.css",
            "resources/assets/css/owl.carousel.min.css",
            "resources/assets/css/owl.theme.default.min.css",
            "resources/assets/css/animate.min.css",
            "resources/assets/css/engagement-ring.css",
            "resources/assets/css/style.css",
        ],
        "public/assets/css/site/site.min.css"
    )
    .styles(
        [
            "resources/assets/css/admin-style.css",
        ],
        "public/assets/css/admin-style.min.css"
    )
    .styles(
        [
            "resources/assets/css/dataTables.css",
        ],
        "public/assets/css/dataTable.min.css"
    )
    .styles(
        [
            "resources/assets/css/rslider.css",
            "resources/assets/css/slick-theme.css",
            "resources/assets/css/slick.min.css",
            "resources/assets/css/jquery-ui.css",
            "resources/assets/css/price-range.css",
            // "resources/assets/css/admin-style.css",
        ],
        "public/assets/css/site/product-detail.min.css"
    )
    .styles(
        [
            "resources/assets/css/all.min.css",
            "resources/assets/css/bootstrap.min.css",
            "resources/assets/css/admin-style.css",
        ],
        "public/assets/css/site/login.min.css"
    )
    .scripts(
        [
            "resources/assets/js/jquery.min.js",
            "resources/assets/js/jquery.form.min.js",
            "resources/assets/js/bootstrap.bundle.min.js",
            "resources/assets/js/common.js",
        ],
        "public/assets/js/site/login.min.js"
    )
    .scripts(
        [
            "resources/assets/js/jquery.min.js",
            "resources/assets/js/owl.carousel.min.js",
            "resources/assets/js/jquery.form.min.js",
            "resources/assets/js/bootstrap.bundle.min.js",
            "resources/assets/js/wow.min.js",
            "resources/assets/js/custom.js",
            "resources/assets/js/common.js",
        ],
        "public/assets/js/site/site.min.js"
    )
    .scripts(
        [
            "resources/assets/js/slick.min.js",
            "resources/assets/js/rSlider.js",
            "resources/assets/js/product_detail.js",
        ],
        "public/assets/js/site/product_detail.min.js"
    )
    .scripts(
        [
            "resources/assets/js/slick.min.js",
            "resources/assets/js/jquery-ui.js",
            "resources/assets/js/price-rane.js",
            "resources/assets/js/diamond_filter.js",
        ],
        "public/assets/js/site/diamond_filter.min.js"
    )
    .scripts(
        [
            "resources/assets/js/jquery.min.js",
            "resources/assets/js/jquery.form.min.js",
            "resources/assets/js/bootstrap.bundle.min.js",
            "resources/assets/js/wow.min.js",
            "resources/assets/js/custom.js",
            "resources/assets/js/common.js",
        ],
        "public/assets/js/admin/admin_common.min.js"
    )
    .scripts(
        ["resources/assets/js/admin/profile.js"],
        "public/assets/js/admin/profile.min.js"
    )
    .scripts([
        "resources/assets/js/slim.min.js",
        "resources/assets/js/admin/product.js",
    ], "public/assets/js/admin/product.min.js")
    .scripts([
        "resources/assets/js/slim.min.js",
        "resources/assets/js/admin/product_detail.js",
    ], "public/assets/js/admin/product_detail.min.js")
    .scripts([
        "resources/assets/js/admin/pincode.js",
    ], "public/assets/js/admin/pincode.min.js")
    .scripts(
        ["resources/assets/js/admin/category.js"],
        "public/assets/js/admin/category.min.js"
    )
    .scripts(
        ["resources/assets/js/admin/coupon.js"],
        "public/assets/js/admin/coupon.min.js"
    )
    .scripts(
        ["resources/assets/js/admin/subcategory.js"],
        "public/assets/js/admin/subcategory.min.js"
    )
    .scripts(
        ["resources/assets/js/admin/banner.js"],
        "public/assets/js/admin/banner.min.js"
    )
    .scripts(
        ["resources/assets/js/admin/user.js"],
        "public/assets/js/admin/user.min.js"
    )
    .scripts(
        ["resources/assets/js/admin/setting.js"],
        "public/assets/js/admin/setting.min.js"
    )
    .scripts(
        ["resources/assets/js/ckeditor.js"],
        "public/assets/js/ckeditor.min.js"
    )
    .scripts(
        ["resources/assets/js/dataTable.js"],
        "public/assets/js/dataTable.min.js"
    );
